# Generated by Django 3.0.5 on 2020-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last surname')),
                ('role', models.CharField(blank=True, choices=[('redaktor', 'Redaktor'), ('redaktor_ve_vycviku', 'Redaktor_ve_vycviku'), ('sefredaktor', 'Šéfredaktor')], max_length=25)),
            ],
            options={
                'ordering': ['role', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Star name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
