# Generated by Django 3.0.5 on 2020-04-30 09:55

from django.db import migrations, models
import django.db.models.deletion
import planety.models


class Migration(migrations.Migration):

    dependencies = [
        ('planety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('imaging', 'Imaging'), ('radial_velocity', 'Radial Velocity'), ('transit', 'Transit'), ('eclipse_timing_variations', 'Eclipse Timing Variations')], max_length=35)),
                ('discovery_date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Discovery date')),
            ],
            options={
                'ordering': ['method'],
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='role',
            field=models.CharField(blank=True, choices=[('redaktor', 'Redaktor'), ('redaktor_ve_vycviku', 'Redaktor ve vycviku'), ('sefredaktor', 'Šéfredaktor')], max_length=25),
        ),
        migrations.CreateModel(
            name='Exoplanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=30, verbose_name='Planet name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=planety.models.img_path, verbose_name='Image')),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planety.Discovery')),
            ],
            options={
                'ordering': ['planet_name', 'discovery'],
            },
        ),
    ]
