# Generated by Django 3.0.5 on 2020-04-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planety', '0003_auto_20200430_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='exoplanet',
            name='distance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Distance'),
        ),
        migrations.AddField(
            model_name='exoplanet',
            name='mass',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mass'),
        ),
        migrations.AddField(
            model_name='exoplanet',
            name='radius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Radius'),
        ),
    ]
